# Generated by Django 6.0.4 on 2026-06-01 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品牌名')),
                ('industry', models.CharField(blank=True, max_length=50, verbose_name='行业')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('logo', models.URLField(blank=True, verbose_name='Logo')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '品牌方',
                'verbose_name_plural': '品牌方',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='anchor', max_length=20, verbose_name='适用角色')),
                ('metric', models.CharField(choices=[('gmv', 'GMV'), ('orders', '订单数'), ('hours', '直播时长'), ('followers', '新增粉丝'), ('conversion', '转化率'), ('attendance', '出勤率')], max_length=20, verbose_name='指标')),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='月度目标')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='权重(%)')),
                ('period', models.CharField(default='monthly', max_length=20, verbose_name='周期')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': 'KPI配置',
                'verbose_name_plural': 'KPI配置',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班次名称')),
                ('type', models.CharField(choices=[('morning', '早班'), ('afternoon', '中班'), ('evening', '晚班'), ('night', '夜班'), ('custom', '自定义')], default='morning', max_length=20, verbose_name='类型')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('color', models.CharField(default='#409EFF', max_length=20, verbose_name='颜色')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('late_minutes', models.IntegerField(default=10, verbose_name='迟到容忍分钟')),
            ],
            options={
                'verbose_name': '班次',
                'verbose_name_plural': '班次',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='小组名')),
                ('leader', models.CharField(blank=True, max_length=50, verbose_name='组长')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='职责描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '运营小组',
                'verbose_name_plural': '运营小组',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('manager', '运营经理'), ('operator', '运营/中控'), ('anchor', '主播'), ('assistant', '助理')], default='anchor', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('wechat', models.CharField(blank=True, max_length=50, verbose_name='微信号')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('id_card', models.CharField(blank=True, max_length=20, verbose_name='身份证号')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='底薪')),
                ('is_active', models.BooleanField(default=True, verbose_name='在职')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='登录账号')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnchorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='直播昵称')),
                ('level', models.CharField(default='普通', max_length=20, verbose_name='主播等级')),
                ('style', models.CharField(blank=True, help_text='如：搞笑/专业/邻家', max_length=100, verbose_name='风格')),
                ('category_tags', models.CharField(blank=True, max_length=200, verbose_name='擅长类目')),
                ('fans_count', models.IntegerField(default=0, verbose_name='粉丝总数')),
                ('follower_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('avg_watch', models.IntegerField(default=0, verbose_name='场均观看')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='转化率(%)')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='合同到期')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_profile', to='scheduling.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '主播档案',
                'verbose_name_plural': '主播档案',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('personal', '事假'), ('sick', '病假'), ('annual', '年假'), ('marriage', '婚假'), ('bereavement', '丧假'), ('maternity', '产假')], max_length=20, verbose_name='请假类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('days', models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='天数')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('approver', models.CharField(blank=True, max_length=50, verbose_name='审批人')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approve_remark', models.CharField(blank=True, max_length=200, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='scheduling.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='直播日期')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='直播时长(分钟)')),
                ('peak_viewers', models.IntegerField(default=0, verbose_name='峰值在线')),
                ('avg_viewers', models.IntegerField(default=0, verbose_name='平均在线')),
                ('new_followers', models.IntegerField(default=0, verbose_name='新增粉丝')),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GMV(元)')),
                ('orders', models.IntegerField(default=0, verbose_name='订单数')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='转化率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling.employee', verbose_name='主播')),
            ],
            options={
                'verbose_name': '直播记录',
                'verbose_name_plural': '直播记录',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(default=0, verbose_name='销量')),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GMV')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='佣金')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scheduling.livesession', verbose_name='直播场次')),
            ],
            options={
                'verbose_name': '商品销售明细',
                'verbose_name_plural': '商品销售明细',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('status', models.CharField(choices=[('scheduled', '已排班'), ('checked_in', '已打卡'), ('completed', '已完成'), ('cancelled', '已取消'), ('absent', '缺勤')], default='scheduled', max_length=20, verbose_name='状态')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling.employee', verbose_name='员工')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling.shift', verbose_name='班次')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班',
                'ordering': ['date', 'shift__start_time'],
            },
        ),
        migrations.AddField(
            model_name='livesession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduling.schedule', verbose_name='排班'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名')),
                ('platform', models.CharField(choices=[('douyin', '抖音'), ('kuaishou', '快手'), ('taobao', '淘宝'), ('xiaohongshu', '小红书'), ('pdd', '拼多多'), ('jd', '京东'), ('video_account', '视频号')], default='douyin', max_length=20, verbose_name='平台')),
                ('store_url', models.URLField(blank=True, verbose_name='店铺链接')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='类目')),
                ('status', models.CharField(choices=[('active', '运营中'), ('paused', '已暂停'), ('closed', '已关停')], default='active', max_length=20, verbose_name='状态')),
                ('monthly_target', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='月度GMV目标(万)')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='scheduling.brand', verbose_name='品牌方')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='scheduling.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='employee',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='employees', to='scheduling.store', verbose_name='负责店铺'),
        ),
        migrations.CreateModel(
            name='StreamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='直播间名称')),
                ('room_id', models.CharField(blank=True, max_length=50, verbose_name='平台房间号')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='scheduling.store', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '直播间',
                'verbose_name_plural': '直播间',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='scheduling.streamroom', verbose_name='直播间'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.streamroom', verbose_name='直播间'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='scheduling.team', verbose_name='所属小组'),
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='格式:2026-06', max_length=20, verbose_name='考核周期')),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GMV达成')),
                ('gmv_target', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GMV目标')),
                ('gmv_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='GMV完成率(%)')),
                ('orders', models.IntegerField(default=0, verbose_name='订单数')),
                ('live_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='直播时长')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='出勤率(%)')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='综合得分')),
                ('level', models.CharField(choices=[('S', 'S-优秀'), ('A', 'A-良好'), ('B', 'B-合格'), ('C', 'C-待改进'), ('D', 'D-不合格')], default='B', max_length=5, verbose_name='评级')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='绩效奖金')),
                ('remark', models.TextField(blank=True, verbose_name='评语')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='scheduling.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '绩效考核',
                'verbose_name_plural': '绩效考核',
                'ordering': ['-period', '-score'],
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('clock_in', '上班打卡'), ('clock_out', '下班打卡')], max_length=20, verbose_name='打卡类型')),
                ('check_time', models.DateTimeField(verbose_name='打卡时间')),
                ('result', models.CharField(choices=[('normal', '正常'), ('late', '迟到'), ('early', '早退'), ('absent', '缺勤'), ('leave', '请假'), ('overtime', '加班')], default='normal', max_length=20, verbose_name='结果')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='打卡位置')),
                ('photo', models.URLField(blank=True, verbose_name='打卡照片')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='迟到分钟')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='scheduling.employee', verbose_name='员工')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='scheduling.schedule', verbose_name='排班')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'ordering': ['-check_time'],
                'indexes': [models.Index(fields=['employee', 'check_time'], name='scheduling__employe_d0edb8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date', 'employee'], name='scheduling__date_a922fc_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date', 'store'], name='scheduling__date_5871be_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['employee', 'date'], name='scheduling__employe_9bbb99_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['store', 'date'], name='scheduling__store_i_237e6e_idx'),
        ),
    ]
