# Generated by Django 6.0.4 on 2026-06-06 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_audienceinsight_benchmarkreport_budgetmanagement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='OpenID')),
                ('unionid', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='UnionID')),
                ('session_key', models.CharField(blank=True, max_length=128, verbose_name='会话密钥')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后登录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.employee', verbose_name='关联员工')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
                'ordering': ['-last_login'],
            },
        ),
    ]
