import { createRouter, createWebHistory } from 'vue-router'

const routes = [
  { path: '/', redirect: '/dashboard' },
  { path: '/dashboard', name: 'dashboard', component: () => import('../views/Dashboard.vue'), meta: { title: '数据驾驶舱' } },
  { path: '/ai', name: 'ai', component: () => import('../views/AI.vue'), meta: { title: 'AI智能中心' } },
  { path: '/stores', name: 'stores', component: () => import('../views/Stores.vue'), meta: { title: '店铺管理' } },
  { path: '/employees', name: 'employees', component: () => import('../views/Employees.vue'), meta: { title: '人员管理' } },
  { path: '/schedules', name: 'schedules', component: () => import('../views/Schedules.vue'), meta: { title: '智能排班' } },
  { path: '/attendance', name: 'attendance', component: () => import('../views/Attendance.vue'), meta: { title: '考勤打卡' } },
  { path: '/sessions', name: 'sessions', component: () => import('../views/Sessions.vue'), meta: { title: '直播业绩' } },
  { path: '/reviews', name: 'reviews', component: () => import('../views/Reviews.vue'), meta: { title: '绩效考核' } },
  { path: '/shifts', name: 'shifts', component: () => import('../views/Shifts.vue'), meta: { title: '班次配置' } },
  // 20个新功能
  { path: '/products', name: 'products', component: () => import('../views/Products.vue'), meta: { title: '商品管理' } },
  { path: '/scripts', name: 'scripts', component: () => import('../views/Scripts.vue'), meta: { title: '直播工具' } },
  { path: '/tasks', name: 'tasks', component: () => import('../views/Tasks.vue'), meta: { title: '任务看板' } },
  { path: '/notifications', name: 'notifications', component: () => import('../views/Notifications.vue'), meta: { title: '消息中心' } },
  { path: '/finance', name: 'finance', component: () => import('../views/Finance.vue'), meta: { title: '财务中心' } },
  { path: '/training', name: 'training', component: () => import('../views/Training.vue'), meta: { title: '培训与目标' } },
  { path: '/competitor', name: 'competitor', component: () => import('../views/Competitor.vue'), meta: { title: '竞品与粉丝' } },
  { path: '/campaigns', name: 'campaigns', component: () => import('../views/Campaigns.vue'), meta: { title: '营销活动' } },
  { path: '/kol', name: 'kol', component: () => import('../views/KOL.vue'), meta: { title: '达人对接' } },
  { path: '/billboard', name: 'billboard', component: () => import('../views/Billboard.vue'), meta: { title: '实时大屏' } },
  { path: '/settings', name: 'settings', component: () => import('../views/Settings.vue'), meta: { title: '系统工具' } },
  // 10个新功能
  { path: '/stream-alerts', name: 'stream-alerts', component: () => import('../views/StreamAlerts.vue'), meta: { title: '直播监控' } },
  { path: '/assets', name: 'assets', component: () => import('../views/Assets.vue'), meta: { title: '设备资产' } },
  { path: '/knowledge', name: 'knowledge', component: () => import('../views/Knowledge.vue'), meta: { title: '知识库' } },
  { path: '/expenses', name: 'expenses', component: () => import('../views/Expenses.vue'), meta: { title: '费用报销' } },
  { path: '/complaints', name: 'complaints', component: () => import('../views/Complaints.vue'), meta: { title: '客户投诉' } },
  { path: '/stream-plans', name: 'stream-plans', component: () => import('../views/StreamPlans.vue'), meta: { title: '直播预告' } },
  { path: '/gifts', name: 'gifts', component: () => import('../views/Gifts.vue'), meta: { title: '打赏统计' } },
  { path: '/fan-groups', name: 'fan-groups', component: () => import('../views/FanGroups.vue'), meta: { title: '粉丝群' } },
  { path: '/reports', name: 'reports', component: () => import('../views/Reports.vue'), meta: { title: '数据报表' } },
  { path: '/suppliers', name: 'suppliers', component: () => import('../views/Suppliers.vue'), meta: { title: '供应商' } },
  // 10个业务功能
  { path: '/selections', name: 'selections', component: () => import('../views/Selections.vue'), meta: { title: '选品管理' } },
  { path: '/samples', name: 'samples', component: () => import('../views/Samples.vue'), meta: { title: '样品管理' } },
  { path: '/ad-campaigns', name: 'ad-campaigns', component: () => import('../views/AdCampaigns.vue'), meta: { title: '流量投放' } },
  { path: '/short-videos', name: 'short-videos', component: () => import('../views/ShortVideos.vue'), meta: { title: '短视频管理' } },
  { path: '/compliance', name: 'compliance', component: () => import('../views/Compliance.vue'), meta: { title: '合规审核' } },
  { path: '/opinions', name: 'opinions', component: () => import('../views/Opinions.vue'), meta: { title: '舆情监控' } },
  { path: '/after-sales', name: 'after-sales', component: () => import('../views/AfterSales.vue'), meta: { title: '售后工单' } },
  { path: '/revenue-sharing', name: 'revenue-sharing', component: () => import('../views/RevenueSharing.vue'), meta: { title: 'MCN分成' } },
  { path: '/brand-projects', name: 'brand-projects', component: () => import('../views/BrandProjects.vue'), meta: { title: '品牌合作' } },
  { path: '/scenes', name: 'scenes', component: () => import('../views/Scenes.vue'), meta: { title: '直播场景' } },
  // 第四轮 20个新功能
  { path: '/live-interactions', name: 'live-interactions', component: () => import('../views/LiveInteractions.vue'), meta: { title: '直播间互动' } },
  { path: '/coupons', name: 'coupons', component: () => import('../views/Coupons.vue'), meta: { title: '优惠券管理' } },
  { path: '/flash-sales', name: 'flash-sales', component: () => import('../views/FlashSales.vue'), meta: { title: '秒杀活动' } },
  { path: '/room-decorations', name: 'room-decorations', component: () => import('../views/RoomDecorations.vue'), meta: { title: '直播间装修' } },
  { path: '/script-tags', name: 'script-tags', component: () => import('../views/ScriptTags.vue'), meta: { title: '话术标签库' } },
  { path: '/sign-contracts', name: 'sign-contracts', component: () => import('../views/SignContracts.vue'), meta: { title: 'MCN签约' } },
  { path: '/negotiations', name: 'negotiations', component: () => import('../views/Negotiations.vue'), meta: { title: '商务洽谈' } },
  { path: '/investments', name: 'investments', component: () => import('../views/Investments.vue'), meta: { title: '招商管理' } },
  { path: '/contract-ledger', name: 'contract-ledger', component: () => import('../views/ContractLedger.vue'), meta: { title: '合同台账' } },
  { path: '/authorizations', name: 'authorizations', component: () => import('../views/Authorizations.vue'), meta: { title: '授权管理' } },
  { path: '/competitor-rooms', name: 'competitor-rooms', component: () => import('../views/CompetitorRooms.vue'), meta: { title: '竞品直播间' } },
  { path: '/traffic', name: 'traffic', component: () => import('../views/Traffic.vue'), meta: { title: '流量分析' } },
  { path: '/user-personas', name: 'user-personas', component: () => import('../views/UserPersonas.vue'), meta: { title: '用户画像' } },
  { path: '/ab-tests', name: 'ab-tests', component: () => import('../views/ABTests.vue'), meta: { title: 'AB测试' } },
  { path: '/data-warnings', name: 'data-warnings', component: () => import('../views/DataWarnings.vue'), meta: { title: '数据预警' } },
  { path: '/settlements', name: 'settlements', component: () => import('../views/Settlements.vue'), meta: { title: '结算单' } },
  { path: '/logistics', name: 'logistics', component: () => import('../views/Logistics.vue'), meta: { title: '物流跟踪' } },
  { path: '/inventories', name: 'inventories', component: () => import('../views/Inventories.vue'), meta: { title: '库存管理' } },
  { path: '/return-analysis', name: 'return-analysis', component: () => import('../views/ReturnAnalysis.vue'), meta: { title: '退货分析' } },
  { path: '/tax-records', name: 'tax-records', component: () => import('../views/TaxRecords.vue'), meta: { title: '税务管理' } },
  // 第五轮 50个新功能
  { path: '/stream-checklists', name: 'stream-checklists', component: () => import('../views/StreamChecklists.vue'), meta: { title: '直播检查清单' } },
  { path: '/stream-replays', name: 'stream-replays', component: () => import('../views/StreamReplays.vue'), meta: { title: '直播回放' } },
  { path: '/stream-backups', name: 'stream-backups', component: () => import('../views/StreamBackups.vue'), meta: { title: '直播备用方案' } },
  { path: '/stream-quality', name: 'stream-quality', component: () => import('../views/StreamQuality.vue'), meta: { title: '直播质量监控' } },
  { path: '/live-timelines', name: 'live-timelines', component: () => import('../views/LiveTimelines.vue'), meta: { title: '直播时间轴' } },
  { path: '/product-links', name: 'product-links', component: () => import('../views/ProductLinks.vue'), meta: { title: '商品链接' } },
  { path: '/stream-templates', name: 'stream-templates', component: () => import('../views/StreamTemplates.vue'), meta: { title: '直播模板' } },
  { path: '/stream-overlays', name: 'stream-overlays', component: () => import('../views/StreamOverlays.vue'), meta: { title: '直播叠加层' } },
  { path: '/live-polls', name: 'live-polls', component: () => import('../views/LivePolls.vue'), meta: { title: '直播投票' } },
  { path: '/orders', name: 'orders', component: () => import('../views/Orders.vue'), meta: { title: '订单管理' } },
  { path: '/refunds', name: 'refunds', component: () => import('../views/Refunds.vue'), meta: { title: '退款管理' } },
  { path: '/price-monitors', name: 'price-monitors', component: () => import('../views/PriceMonitors.vue'), meta: { title: '价格监控' } },
  { path: '/commission-configs', name: 'commission-configs', component: () => import('../views/CommissionConfigs.vue'), meta: { title: '佣金配置' } },
  { path: '/product-tags', name: 'product-tags', component: () => import('../views/ProductTags.vue'), meta: { title: '商品标签' } },
  { path: '/product-reviews', name: 'product-reviews', component: () => import('../views/ProductReviews.vue'), meta: { title: '商品评价' } },
  { path: '/sales-targets', name: 'sales-targets', component: () => import('../views/SalesTargets.vue'), meta: { title: '销售目标' } },
  { path: '/promo-codes', name: 'promo-codes', component: () => import('../views/PromoCodes.vue'), meta: { title: '推广码' } },
  { path: '/content-calendars', name: 'content-calendars', component: () => import('../views/ContentCalendars.vue'), meta: { title: '内容日历' } },
  { path: '/influencer-collabs', name: 'influencer-collabs', component: () => import('../views/InfluencerCollabs.vue'), meta: { title: '达人合作' } },
  { path: '/social-medias', name: 'social-medias', component: () => import('../views/SocialMedias.vue'), meta: { title: '社媒管理' } },
  { path: '/email-campaigns', name: 'email-campaigns', component: () => import('../views/EmailCampaigns.vue'), meta: { title: '邮件营销' } },
  { path: '/referral-programs', name: 'referral-programs', component: () => import('../views/ReferralPrograms.vue'), meta: { title: '推荐计划' } },
  { path: '/loyalty-programs', name: 'loyalty-programs', component: () => import('../views/LoyaltyPrograms.vue'), meta: { title: '会员积分' } },
  { path: '/events', name: 'events', component: () => import('../views/Events.vue'), meta: { title: '活动管理' } },
  { path: '/seo', name: 'seo', component: () => import('../views/SEO.vue'), meta: { title: 'SEO优化' } },
  { path: '/realtime-analytics', name: 'realtime-analytics', component: () => import('../views/RealtimeAnalytics.vue'), meta: { title: '实时分析' } },
  { path: '/audience-insights', name: 'audience-insights', component: () => import('../views/AudienceInsights.vue'), meta: { title: '受众洞察' } },
  { path: '/conversion-funnels', name: 'conversion-funnels', component: () => import('../views/ConversionFunnels.vue'), meta: { title: '转化漏斗' } },
  { path: '/roi-analysis', name: 'roi-analysis', component: () => import('../views/ROIAnalysis.vue'), meta: { title: 'ROI分析' } },
  { path: '/benchmark-reports', name: 'benchmark-reports', component: () => import('../views/BenchmarkReports.vue'), meta: { title: '基准报告' } },
  { path: '/custom-dashboards', name: 'custom-dashboards', component: () => import('../views/CustomDashboards.vue'), meta: { title: '自定义看板' } },
  { path: '/data-imports', name: 'data-imports', component: () => import('../views/DataImports.vue'), meta: { title: '数据导入' } },
  { path: '/salary', name: 'salary', component: () => import('../views/Salary.vue'), meta: { title: '薪资管理' } },
  { path: '/recruitments', name: 'recruitments', component: () => import('../views/Recruitments.vue'), meta: { title: '招聘管理' } },
  { path: '/onboardings', name: 'onboardings', component: () => import('../views/Onboardings.vue'), meta: { title: '员工入职' } },
  { path: '/leave-balances', name: 'leave-balances', component: () => import('../views/LeaveBalances.vue'), meta: { title: '假期余额' } },
  { path: '/team-chat', name: 'team-chat', component: () => import('../views/TeamChat.vue'), meta: { title: '团队沟通' } },
  { path: '/okr', name: 'okr', component: () => import('../views/OKR.vue'), meta: { title: 'OKR管理' } },
  { path: '/budgets', name: 'budgets', component: () => import('../views/Budgets.vue'), meta: { title: '预算管理' } },
  { path: '/profits', name: 'profits', component: () => import('../views/Profits.vue'), meta: { title: '利润分析' } },
  { path: '/invoices', name: 'invoices', component: () => import('../views/Invoices.vue'), meta: { title: '发票管理' } },
  { path: '/payments', name: 'payments', component: () => import('../views/Payments.vue'), meta: { title: '收款记录' } },
  { path: '/insurances', name: 'insurances', component: () => import('../views/Insurances.vue'), meta: { title: '保险记录' } },
  { path: '/legal-cases', name: 'legal-cases', component: () => import('../views/LegalCases.vue'), meta: { title: '法务案件' } },
  { path: '/quality-checks', name: 'quality-checks', component: () => import('../views/QualityChecks.vue'), meta: { title: '质量检查' } },
  { path: '/workflows', name: 'workflows', component: () => import('../views/Workflows.vue'), meta: { title: '工作流自动化' } },
  { path: '/vendor-ratings', name: 'vendor-ratings', component: () => import('../views/VendorRatings.vue'), meta: { title: '供应商评级' } },
  { path: '/stock-alerts', name: 'stock-alerts', component: () => import('../views/StockAlerts.vue'), meta: { title: '库存预警' } },
  { path: '/sla', name: 'sla', component: () => import('../views/SLA.vue'), meta: { title: 'SLA管理' } },
  { path: '/feedbacks', name: 'feedbacks', component: () => import('../views/Feedbacks.vue'), meta: { title: '反馈系统' } },
]

const router = createRouter({
  history: createWebHistory(),
  routes,
})

router.afterEach((to) => {
  document.title = `${to.meta.title || 'MCN管家'} - MCN 管家`
})

export default router
